In [2]:
import numpy as np 

a = np.random.randint(0, 10, 5)
b = np.random.randint(0, 10, (2,4))
print(a)
print(b)
print(a.ndim)
print(b.ndim)
print(a+b)

[4 4 7 6 5]
[[9 5 5 7]
 [5 9 5 5]]
1
2


ValueError: operands could not be broadcast together with shapes (5,) (2,4) 

In [14]:
import pandas as pd
import numpy as np

b = np.random.randint(0, 10, (5,5)) 
print(b)
print(b[2,:]) # fila
print(b[:,3]) # columna
print((b[2,:]) + (b[:,3])) # suma de los valores

[[5 8 1 2 4]
 [8 4 0 9 6]
 [4 1 3 1 3]
 [0 0 7 4 3]
 [9 1 4 3 6]]
[4 1 3 1 3]
[2 9 1 4 3]
[ 6 10  4  5  6]
