In [2]:
import numpy as np 

a = np.random.randint(0, 10, 5)
b = np.random.randint(0, 10, (2,4))
print(a)
print(b)
print(a.ndim)
print(b.ndim)
print(a+b)

[4 4 7 6 5]
[[9 5 5 7]
 [5 9 5 5]]
1
2


ValueError: operands could not be broadcast together with shapes (5,) (2,4) 

In [4]:
import pandas as pd
import numpy as np

b = np.random.randint(0, 10, (5,5)) 
print(b)
print(b[2,:]) # fila
print(b[:,3]) # columna
print((b[2,:]) + (b[:,3])) # suma de los valores

[[3 8 1 3 1]
 [4 8 0 7 9]
 [0 8 8 0 2]
 [0 3 2 8 8]
 [9 6 0 6 8]]
[0 8 8 0 2]
[3 7 0 8 6]
[ 3 15  8  8  8]


In [2]:
import numpy as np
e = np.full((2,2),7)
print(e)

[[7 7]
 [7 7]]


In [5]:
print(b)

[[3 8 1 3 1]
 [4 8 0 7 9]
 [0 8 8 0 2]
 [0 3 2 8 8]
 [9 6 0 6 8]]


In [6]:
bMask = b%4==0
print(bMask)

[[False  True False False False]
 [ True  True  True False False]
 [ True  True  True  True False]
 [ True False False  True  True]
 [False False  True False  True]]


In [7]:
print(bMask[2,:])
print(bMask[:,3])

[ True  True  True  True False]
[False False  True  True False]


In [11]:
print(b[bMask])

[8 4 8 0 0 8 8 0 0 8 8 0 8]


In [12]:
print(bMask[b])

IndexError: index 8 is out of bounds for axis 0 with size 5