In [58]:
import numpy as np 

a = np.random.randint(0, 10, 5)
b = np.random.randint(0, 10, (2,4))
print(a)
print(b)
print(a.ndim)
print(b.ndim)
print(a+b)

[0 6 3 1 5]
[[5 2 2 4]
 [5 7 7 1]]
1
2


ValueError: operands could not be broadcast together with shapes (5,) (2,4) 

In [53]:
b = np.random.randint(0, 10, (1,1))
c = np.random.randint(0, 10, (2, 5, 3))
print(b)
print(c)
print(c.ndim)
print(b.ndim)
print(b+c)

[[3]]
[[[1 3 2]
  [4 1 7]
  [0 9 9]
  [4 1 8]
  [5 2 3]]

 [[6 3 3]
  [0 5 3]
  [0 7 0]
  [6 7 6]
  [5 3 0]]]
3
2
[[[ 4  6  5]
  [ 7  4 10]
  [ 3 12 12]
  [ 7  4 11]
  [ 8  5  6]]

 [[ 9  6  6]
  [ 3  8  6]
  [ 3 10  3]
  [ 9 10  9]
  [ 8  6  3]]]
