In [32]:
import numpy as np # importo libreria NumPy

b = np.random.randint(0, 10, (5,5))

In [33]:
print(b)

[[1 0 6 1 7]
 [1 4 8 0 8]
 [7 9 2 5 2]
 [9 0 2 9 3]
 [7 4 5 2 9]]


In [35]:
print(b.max())

9


In [36]:
print(b.max(axis=0))
print(b.max(axis=1))

[9 9 8 9 9]
[7 8 9 9 9]


In [37]:
print(b.max(axis=0))

[9 9 8 9 9]


In [38]:
print(b.max(axis=1))

[7 8 9 9 9]
