# Ejercicio 1

### *Crea un np.array de una dimension, que incluya alomenos 8 numeros enteros, data type int64*

In [1]:
import numpy as np # importo libreria NumPy

a = np.array([1,2,3,4,5,6,7,8], dtype = np.int64) # creo el array

### *Muestra la dimension*

In [4]:
print(a.ndim)

1


### *Muestra la forma de la matriz*

In [3]:
print(a.shape)

(8,)


# Ejercicio 2

### *De la matriz del ejercicio 1, calcula el valor medio de los valores introducidos y resta la mediana resultante de cada unos de los valores de la matriz*

In [8]:
print(a.mean()) # valor medio

4.5


In [10]:
print(a - a.mean()) # resta 

[-3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5]


# Ejercicio 3

### *Crea una matriz bidimensaional con una forma de 5 x 5. Extrae el valor maximo de la matriz, y los valores maximos de cada unos de sus ejes*

In [17]:
import numpy as np # importo libreria NumPy

b = np.random.randint(0, 10, (5,5)) # creo el array con numeros enteros aleatorios
print(b)

[[6 5 8 8 1]
 [9 0 1 3 1]
 [2 8 4 6 0]
 [6 1 3 2 4]
 [6 1 0 2 5]]


In [18]:
print(b.max()) # valor maximo de la matriz

9


In [19]:
print(b.max(axis=0)) # valores maximos de cada eje
print(b.max(axis=1))

[9 8 8 8 5]
[8 9 8 6 6]


# Ejercicio 4

### *Mostrar con ejemplos de diferentes matrices, la regla fundamental de Broadcasting que dice: "las matrices se pueden transmitir/brodcast si sus dimensiones coinciden o si una de las matrices tiene una medida de 1"*

In [1]:
import numpy as np 

a = np.random.randint(0, 10, 5)
b = np.random.randint(0, 10, 5)
print(a)
print(b)
print(a+b)

[4 0 7 8 8]
[0 5 5 1 2]
[ 4  5 12  9 10]


In [2]:
a = np.random.randint(0, 10, 5)
b = np.random.randint(0, 10, 1)
print(a)
print(b)
print(a+b)

[0 9 2 6 2]
[8]
[ 8 17 10 14 10]


In [4]:
a = np.random.randint(0, 10, 5)
b = np.random.randint(0, 10, 2)
print(a)
print(b)
print(a+b)

[4 5 7 0 6]
[4 3]


ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [5]:
b = np.random.randint(0, 10, (1,3)) 
c = np.random.randint(0, 10, (1, 5, 3))
print(b)
print(c)
print(c.ndim)
print(b.ndim)
print(b+c)

[[3 3 3]]
[[[5 2 3]
  [7 3 4]
  [8 9 3]
  [6 4 4]
  [8 2 1]]]
3
2
[[[ 8  5  6]
  [10  6  7]
  [11 12  6]
  [ 9  7  7]
  [11  5  4]]]


# Ejercicio 5

### *Utiliza la indexación para extraer los valores de una columa y una fila de la matriz. I suma sus valores*

In [2]:
import pandas as pd
import numpy as np

b = np.random.randint(0, 10, (5,5)) # creo una matriz bidimensional con numeros aleatorios del 0 al 10
print(b) # matriz
print(b[2,:]) # fila
print(b[:,3]) # columna
print((b[2,:]) + (b[:,3])) # suma de los valores   

[[1 6 9 4 3]
 [5 2 3 7 3]
 [3 9 4 1 9]
 [2 7 5 0 8]
 [6 5 6 1 6]]
[3 9 4 1 9]
[4 7 1 0 1]
[ 7 16  5  1 10]


# Ejercicio 6

### *Mask la matriz anterior, realiza un calculo booleano vectorizado, cogiendo cada elemento y comprovando si se divide uniformemente por 4.*

### *Esto retorna una matriz de mask de la misma forma que con los resultados elementales del calculo.*

In [3]:
print(b) # matriz anterior

[[1 6 9 4 3]
 [5 2 3 7 3]
 [3 9 4 1 9]
 [2 7 5 0 8]
 [6 5 6 1 6]]


In [4]:
bMask = b%4 == 0 # se divide cada valor entre 4, y si el resto da 0 el resultado sera True
print(bMask)

[[False False False  True False]
 [False False False False False]
 [False False  True False False]
 [False False False  True  True]
 [False False False False False]]


# Ejercicio 7

### *A continuacion, utilizar esa mascara para indexar a la matriz de numeros original. Eso hace que la matriz pierda su forma original, reduciendola a una dimension, pero aun se obtendran los datos que se buscan*

In [6]:
print(b[bMask])

[4 4 0 8]
