# Ejercicio 1

### *Crea un np.array de una dimension, que incluya alomenos 8 numeros enteros, data type int64*

In [1]:
import numpy as np # importo libreria NumPy

a = np.array([1,2,3,4,5,6,7,8], dtype = np.int64) # creo el array

### *Muestra la dimension*

In [4]:
print(a.ndim)

1


### *Muestra la forma de la matriz*

In [3]:
print(a.shape)

(8,)


# Ejercicio 2

### *De la matriz del ejercicio 1, calcula el valor medio de los valores introducidos y resta la mediana resultante de cada unos de los valores de la matriz*

In [8]:
print(a.mean()) # valor medio

4.5


In [10]:
print(a - a.mean()) # resta 

[-3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5]


# Ejercicio 3

### *Crea una matriz bidimensaional con una forma de 5 x 5. Extrae el valor maximo de la matriz, y los valores maximos de cada unos de sus ejes*

In [17]:
import numpy as np # importo libreria NumPy

b = np.random.randint(0, 10, (5,5)) # creo el array con numeros enteros aleatorios
print(b)

[[6 5 8 8 1]
 [9 0 1 3 1]
 [2 8 4 6 0]
 [6 1 3 2 4]
 [6 1 0 2 5]]


In [18]:
print(b.max()) # valor maximo de la matriz

9


In [19]:
print(b.max(axis=0)) # valores maximos de cada eje
print(b.max(axis=1))

[9 8 8 8 5]
[8 9 8 6 6]


# Ejercicio 4

### *Mostrar con ejemplos de diferentes matrices, la regla fundamental de Broadcasting que dice: "las matrices se pueden transmitir/brodcast si sus dimensiones coinciden o si una de las matrices tiene una medida de 1"*

##### *Si las matrices son de la misma dimension y de la misma medida, o una de ellas tiene una medida de 1, pueden hacer broadcast*

In [1]:
import numpy as np 

a = np.random.randint(0, 10, 5) # 1 dimension
b = np.random.randint(0, 10, 5)
print(a)
print(b)
print(a+b)

[3 9 6 8 1]
[5 2 0 5 6]
[ 8 11  6 13  7]


In [3]:
a = np.random.randint(0, 10, 5)
b = np.random.randint(0, 10, 1) # 1 dimension medida de 1
print(a)
print(b)
print(a+b)

[1 3 5 4 7]
[7]
[ 8 10 12 11 14]


##### *Si son de diferentes dimensiones o una de las matrices es de otra medida que no sea 1, no podran hacer broadcast*

In [4]:
a = np.random.randint(0, 10, 5)
b = np.random.randint(0, 10, 2) # medida diferente de 1
print(a)
print(b)
print(a+b)

[1 8 2 8 1]
[5 6]


ValueError: operands could not be broadcast together with shapes (5,) (2,) 